### ISSUE TITLE
Especificação de Caso de Uso - (Nº divergente)

### ISSUE THREAD

**Issue by lhneves** [ccfei652/Sistema-de-Judocas#3]
Os código dos casos de uso não conferem com os códigos descritos nas especificações de requisitos.

Exemplo: 
Especificação de Requisito -> E2 Atualizar Aluno
Especificação de Caso de Uso -> E2 Buscar Aluno

**Comment by Henry7k** [comment]
Resolvido. Alterando os códigos na especificação de caso de uso. A mudança pode ser vista no histórico de revisões da Wiki.
